export default [
  {
    position: 2,
    title: 'Mediter-ranean avenue',
    companyTypeId: 1,
    amount: 60,
    color: '#91573b',
  },
  {
    position: 4,
    title: 'Baltic avenue',
    companyTypeId: 1,
    amount: 60,
    color: '#91573b',
  },
  {
    position: 7,
    title: 'Oriental avenue',
    companyTypeId: 2,
    amount: 100,
    color: '#a8e1f5',
  },
  {
    position: 9,
    title: 'Vermont avenue',
    companyTypeId: 2,
    amount: 100,
    color: '#a8e1f5',
  },
  {
    position: 10,
    title: 'Connecticut avenue',
    companyTypeId: 2,
    amount: 120,
    color: '#a8e1f5',
  },
  {
    position: 12,
    title: 'St. Charles place',
    companyTypeId: 3,
    amount: 140,
    color: '#d64099',
  },
  {
    position: 14,
    title: 'States avenue',
    companyTypeId: 3,
    amount: 140,
    color: '#d64099',
  },
  {
    position: 15,
    title: 'Virgina avenue',
    companyTypeId: 3,
    amount: 160,
    color: '#d64099',
  },
  {
    position: 17,
    title: 'St. James place',
    companyTypeId: 4,
    amount: 180,
    color: '#f3933d',
  },
  {
    position: 19,
    title: 'Nennesse avenue',
    companyTypeId: 4,
    amount: 180,
    color: '#f3933d',
  },
  {
    position: 20,
    title: 'New York avenue',
    companyTypeId: 4,
    amount: 200,
    color: '#f3933d',
  },
  {
    position: 22,
    title: 'Kentucky avenue',
    companyTypeId: 5,
    amount: 220,
    color: '#e93732',
  },
  {
    position: 24,
    title: 'Indiana avenue',
    companyTypeId: 5,
    amount: 220,
    color: '#e93732',
  },
  {
    position: 25,
    title: 'Illinois avenue',
    companyTypeId: 5,
    amount: 240,
    color: '#e93732',
  },
  {
    position: 27,
    title: 'Atlantic avenue',
    companyTypeId: 5,
    amount: 260,
    color: '#fbf14f',
  },
  {
    position: 28,
    title: 'Venthor avenue',
    companyTypeId: 5,
    amount: 260,
    color: '#fbf14f',
  },
  {
    position: 30,
    title: 'Marvin avenue',
    companyTypeId: 5,
    amount: 280,
    color: '#fbf14f',
  },
  {
    position: 32,
    title: 'Pacific avenue',
    companyTypeId: 6,
    amount: 300,
    color: '#51b258',
  },
  {
    position: 33,
    title: 'North Carolina avenue',
    companyTypeId: 6,
    amount: 300,
    color: '#51b258',
  },
  {
    position: 35,
    title: 'Pennsylvania avenue',
    companyTypeId: 6,
    amount: 320,
    color: '#51b258',
  },
  {
    position: 38,
    title: 'Park place',
    companyTypeId: 7,
    amount: 350,
    color: '#2272bf',
  },
  {
    position: 39,
    title: 'Board walk',
    companyTypeId: 7,
    amount: 400,
    color: '#2272bf',
  },
];
